### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by wjagodfrey** [nfl/react-gpt#10]
Hi there,

Trying to figure out server-side rendering.

Your README says:

`Run [...] npm start for server side rendering.`

Though doing so, and inspecting page source reveals that the page templates but not the ads are being rendered server-side.

Any pointers on getting this working?

Many thanks,
WIlfred

**Comment by taak77** [comment]
@wjagodfrey Thanks for your interest in this library.

The SSR example is there to illustrate how the library works with SSR and make sure there is no error with it.
The actual ad won't render on the server side as `react-gpt` relies on [Google Publisher Tags](https://developers.google.com/doubleclick-gpt/?hl=en) to render an ad which happens after downloading and executing their library on the client side.

Apologies for the confusion.

**Comment by wjagodfrey** [comment]
That makes sense, thanks for clearing that up

**Comment by taak77** [comment]
@wjagodfrey no problem
