### ISSUE TITLE
refreshing specific ad unit with refresh( slots )

### ISSUE THREAD

**Issue by rishisharma08** [nfl/react-gpt#13]
i know the syntax for refreshing a specific ad unit is
**refresh([slots, options])** where _slots_ is an array of slots to refresh.

How do i refresh one of 5 ads on the page? 
suppose i have this 5 times somewhere on the page and in only want to refresh the second one
```
<GPT
  adUnitPath={adUnitPath}
  slotSize={[300,250]}
/>
```

how do i get the reference to the slot ?

**Comment by rishisharma08** [comment]
ok, for second part of the question, i played around with **ref** and see that i can get a reference to the slot using ref
```
<GPT
  ref={(slot) => { console.log( slot.adSlot ); }}
  adUnitPath={adUnitPath}
  slotSize={[300,250]}
/>
```

so now, whats the recommended way of refreshing a particular slot in a page of 5 ads.. ?

**Comment by rishisharma08** [comment]
hmm even the ref's slot.adSlot returns an undefined at initial load.

**Comment by rishisharma08** [comment]
alright. that works.
just a side note, react updated their docs and recommend the use of ref callback instead of this.refs.myRef
[https://facebook.github.io/react/docs/refs-and-the-dom.html](https://facebook.github.io/react/docs/refs-and-the-dom.html)
_If you are currently using this.refs.myRefName to access refs, we recommend using this pattern instead._

**Comment by tyleraadams** [comment]
After reading this, I am trying to access reference to slot in this fashion

```<GPT
      ref={(slot) => { console.log( slot.adSlot ); }} 
      adUnitPath={adUnitPath}
      slotSize={[300,250]}
      /> // >>> logs undefined```

Is `adSlot` a private var now? Or how can I access?

**Comment by taak77** [comment]
@tyleraadams, ad renders asynchronously after the seed file is loaded, `adSlot` will be available after an ad is rendered and you should be able to access it within `onSlotRenderEnded` callback prop.

**Comment by rishisharma08** [comment]
@tyleraadams ref gets called when mount happens and also when unmount happens. so when unmount happens, ull get a null value in ref -- and hence, the undefined in the log
https://facebook.github.io/react/docs/refs-and-the-dom.html
