### ISSUE TITLE
Multiple sizes for one slot?

### ISSUE THREAD

**Issue by Joralf** [nfl/react-gpt#14]
Awesome repo with loads of functionality! I just had one minor headache before implementing. The API docs say:

`slotSize(optional) - An optional array of width and height size for the ad slot. This will be preceded by the sizeMapping if specified.`

Which reads as "you can only specify one size".

Whilst the example over here (https://github.com/nfl/react-gpt/blob/master/examples/apps/routing/app.js) shows multiple sizes defined for one adSlot:

`slotSize={[[728, 90], [970, 90]]}`

If it's the latter, which I assume it is, maybe the documentation would be more clear if it says "An optional array or array of array's containing width and height size(s) for the ad slot".

**Comment by taak77** [comment]
@Joralf thanks for the suggestion, `slotSize` supports the types defined [here](https://developers.google.com/doubleclick-gpt/reference#type-definitions), will add that to the docs.
