### ISSUE TITLE
Support googletag.events.SlotOnloadEvent

### ISSUE THREAD

**Issue by taak77** [nfl/react-gpt#20]
add support for [`googletag.events.SlotOnloadEvent`](https://developers.google.com/doubleclick-gpt/reference#googletageventsslotonloadevent).

**Comment by potench** [comment]
For someone looking to add support for this event, you might be able to essentially follow how the `slotRenderEnded` event is supported:  
https://github.com/nfl/react-gpt/search?utf8=%E2%9C%93&q=SLOT_RENDER_ENDED

**Comment by potench** [comment]
@gabelew thanks for the PR
