### ISSUE TITLE
mockGPT.js should not be in production bundle

### ISSUE THREAD

**Issue by dalimian** [nfl/react-gpt#29]
when I do `import {Bling as GPT} from "react-gpt";` from my production bundle, I see that mockGPT.js makes it into the bundle, could you please provide a way to import only minimal things needed for production.

**Comment by eliseumds** [comment]
Have you tried `import { default as GPT } from 'react-gpt/lib/Bling';`?

**Comment by dalimian** [comment]
Yea, same outcome

**Comment by damusnet** [comment]
Hi, with `import { Bling } from 'react-gpt';`, even with `v1.1.1`, it looks like `mockGPT.js` is still present in our production bundle (with Next.js / webpack / UglifyJSPlugin tree shaking enabled). Is there another recommended way to import the library? Am I missing something?

![image](https://user-images.githubusercontent.com/433409/34461712-4f4f5e76-ee32-11e7-841f-e6fe4293518e.png)

Thanks for your help.

**Comment by potench** [comment]
@damusnet I will try to fix this today, looks like `createManagerTest` is getting imported into the distributed payload.

**Comment by damusnet** [comment]
Thank you very much @potench for looking into it and fixing it. Much appreciated :)
