### ISSUE TITLE
Questions on dummy ad slots created

### ISSUE THREAD

**Issue by canyousayyes** [nfl/react-gpt#30]
Hello, I have setup a simple web page using this library.
When checking the results in `googletag.openConsole()`, I found that there's a strange slot `/_0` created and destroyed later.
<img width="473" alt="screen shot 2017-05-26 at 11 00 48 am" src="https://cloud.githubusercontent.com/assets/3950187/26480035/09abce74-420a-11e7-81c9-46892d44bf36.png">

There's no fetch and render actions on the ad slot, but I am curious about why it will be here.
Thank you.

**Comment by potench** [comment]
This is the result of a `dummyAdSlot` being created in order to guarantee that `googletag.PubAdsService` is loaded and enabled. 

https://github.com/nfl/react-gpt/blob/5ae8f882030e3b9994ffba218e04653083099a3e/src/createManager.js#L334-L337

**Comment by canyousayyes** [comment]
Alright, look it will not affect actual impression metrics. Thank you :)
