### ISSUE TITLE
Lots of script tags on document's head - expected?

### ISSUE THREAD

**Issue by pgsill** [nfl/react-gpt#58]
Browsing https://thescoreesports.com and inspecting the head tag, we can see an increasing number (as you navigate between pages and load ads) of script tags popping up. 

After ~5 pages this number can grow to over 50, which made me wonder if this behavior is expected and doesn't negatively impact performance.

![pic](https://i.imgur.com/9mdQgQi.png)

**Comment by potench** [comment]
I see the same thing on nfl.com.  

The Network panel says the initiator of these calls is `pubads_impl_161.js:1`.  I believe GPT's script loader adds them to the <head> 
Might require a little more research to validate, but that's my current hunch. 

Lighthouse suggests a limit to the number of elements on a page. "target: < 1,500 nodes" so if this continues to grow then that would result in a render slowdown over time.

**Comment by nandosangenetto** [comment]
@taak77 @jamsea could you please help us?
