### ISSUE TITLE
Somtimes ads are not rendered, yet they seem to have loaded

### ISSUE THREAD

**Issue by aaronatmycujoo** [nfl/react-gpt#62]
I can see the network request in the tab in Chrome, although an empty iframe is rendered which contains

```
<html><head></head><body marginwidth="0" marginheight="0"></body></html>
```

The code in my page ends up being:

```
<div id="top-home-leaderboard">
    <div id="bling-1" style="text-align: center; margin-bottom: 32px;" data-google-query-id="uuid">
        <div id="google_ads_iframe_/x/y/z" style="border: 0pt none;">
            <iframe id="google_ads_iframe_/x/y/z" title="3rd party ad content" name="google_ads_iframe_/x/y/z" width="728" height="90" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" srcdoc="" style="border: 0px; vertical-align: bottom;"></iframe>
        </div>
    </div>
</div>
```

And my config is:

```
        adUnitPath: '/x/y/z',
        id: 'top-home-leaderboard',
        setCollapseEmptyDiv: true,
        sizeMapping: [
            {viewport: [400, 0], slot: [300, 250]},
            {viewport: [600, 0], slot: [320, 50]},
            {viewport: [1200, 1], slot: [728, 90]},
        ],
        style: {
            textAlign: 'center',
            marginBottom: '32px',
        },
```

Is this something I am doing wrong?

**Comment by potench** [comment]
@aaronatmycujoo this sounds like an ad-configuration issue.
1. Can you try running your ad tag through the VAST inspector here? https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector 

2. You can also try the IMA3 debug mode by adding `?googfc` to your browser URL

3. If you still need help, post the `adUnitPath` you're using 

Closing for now, feel free to reopen if this ends up being a react-gpt issue.

**Comment by aaronatmycujoo** [comment]
I served my server through ngrok, as I was accessing it through localhost, and now the ads are serving every time.

If I comes across this again I will follow your steps.

Thanks.
