### ISSUE TITLE
Prettier should be a dev dependency, not a regular dependency.

### ISSUE THREAD

**Issue by chiel** [nfl/react-gpt#66]
We're using `react-gpt` at work, and for some reason `prettier` was being run on save. I traced it down to the fact that `react-gpt` installs it as a dependency, rather than a dev dependency.

Would you guys accept a PR that rectifies this?

**Comment by potench** [comment]
Yep, or you can review the above PR. You didn't have to close #65, do you want that reviewed and added? Just separate out the version bump from the commit.

**Comment by chiel** [comment]
Yeah, the reason I forked this repo is cause we are dependent on the fix for work, so I republished it under out namespace until it would be merged. It had been a while so I figured there was no interest.

I'll happily make two pull requests for the two separate things, that way they can stay topical.

Let me know what you guys prefer and I'll make it happen!
