### ISSUE TITLE
Support for GDPR compliant nonPersonalizedAds

### ISSUE THREAD

**Issue by jonsherrard** [nfl/react-gpt#81]
React GPT users inside the EU will need to be able request nonPersonalized ads... tomorrow.

Here's the documentation: https://support.google.com/dfp_premium/answer/7678538

We'll create a fork and try and get something working - but wanted to flag it.

We'll need to be able to replace https://github.com/nfl/react-gpt/blob/22437553b50272b8d6221ed29f98da76c912eabd/src/Bling.js#L690 with a call to:

`googletag.pubads().setRequestNonPersonalizedAds(1)`

**Comment by tomRzeznik** [comment]
When you intend to implement the setRequestNonPersonalizedAds method in react-gpt? Support for GDPR is an important issue for European Union countries.

**Comment by aaronatmycujoo** [comment]
Is it possible to request non personalised ads with react-gpt yet?

**Comment by miblanchard** [comment]
Closing this issue as https://github.com/nfl/react-gpt/pull/97 fixes
