### ISSUE TITLE
Page level targeting is not getting set

### ISSUE THREAD

**Issue by shaheerMpls** [nfl/react-gpt#9]
I may be wrong but I tried to set the page level targeting parameter which passes as cust_params in the request header is not passing. Right now the targeting is only for the slot level which goes as scp in the request header. 

_cust_params_ will the the parameter which is targeted as `googletag.pubads().setTargeting `

**Comment by taak77** [comment]
@shaheerMpls, thanks for your interest in this library.

Passing targeting as prop for the component only sets the slot level targeting, for the page level targeting you can call static `setTargeting`.

```
import {Bling as GPT} from "react-gpt";

GPT.setTargeting("interests", "sports");
```

**Comment by shaheerMpls** [comment]
💯 👍 solution works like champ, thanks.
